import { Issue, User, Contractor, Bid } from './types';
import { generateAIInsights } from './ai';
import { generateEnhancedAIInsights } from './enhancedAI';
import type { NGO } from './types';

// JANMARG Mock Data - Comprehensive civic issues dataset
// Total Issues: 17 (5 Resolved, 4 In Progress, 8 Unresolved)

export const mockNGOs: NGO[] = [
  {
    id: 'ngo1',
    name: 'Clean India Foundation',
    description: 'Dedicated to improving sanitation and cleanliness across India through community engagement and awareness programs.',
    category: 'Sanitation & Hygiene',
    contact: '+91-9876500001',
    email: 'contact@cleanindia.org',
    location: 'New Delhi',
    state: 'Delhi',
    registrationNumber: 'NGO/DL/2015/12345',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo2',
    name: 'Road Safety India',
    description: 'Working towards safer roads and better infrastructure through advocacy, education, and community projects.',
    category: 'Infrastructure & Safety',
    contact: '+91-9876500002',
    email: 'info@roadsafetyindia.org',
    location: 'Mumbai',
    state: 'Maharashtra',
    registrationNumber: 'NGO/MH/2012/67890',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo3',
    name: 'Water For All Trust',
    description: 'Ensuring access to clean drinking water and sanitation facilities for underprivileged communities across India.',
    category: 'Water & Environment',
    contact: '+91-9876500003',
    email: 'support@waterforall.org',
    location: 'Bangalore',
    state: 'Karnataka',
    registrationNumber: 'NGO/KA/2018/11223',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo4',
    name: 'Bright Streets Initiative',
    description: 'Illuminating communities by installing solar street lights in rural and urban areas to improve safety and reduce crime.',
    category: 'Energy & Safety',
    contact: '+91-9876500004',
    email: 'hello@brightstreets.org',
    location: 'Pune',
    state: 'Maharashtra',
    registrationNumber: 'NGO/MH/2020/33445',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo5',
    name: 'Urban Green Alliance',
    description: 'Creating sustainable cities through tree plantation drives, waste management programs, and environmental education.',
    category: 'Environment & Sustainability',
    contact: '+91-9876500005',
    email: 'contact@urbangreenalliance.org',
    location: 'Chennai',
    state: 'Tamil Nadu',
    registrationNumber: 'NGO/TN/2016/55667',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo6',
    name: 'Community Health Corps',
    description: 'Providing healthcare services and medical assistance to underserved populations across India.',
    category: 'Healthcare & Wellness',
    contact: '+91-9876500006',
    email: 'info@healthcorps.org',
    location: 'Kolkata',
    state: 'West Bengal',
    registrationNumber: 'NGO/WB/2014/77889',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo7',
    name: 'Jal Jeevan Mission Support',
    description: 'Supporting government initiatives to provide safe drinking water to every household in rural India.',
    category: 'Water & Rural Development',
    contact: '+91-9876500007',
    email: 'support@jaljeevan.org',
    location: 'Jaipur',
    state: 'Rajasthan',
    registrationNumber: 'NGO/RJ/2019/22334',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo8',
    name: 'Digital Infrastructure Foundation',
    description: 'Bridging the digital divide by establishing internet connectivity and digital literacy programs in underserved areas.',
    category: 'Technology & Infrastructure',
    contact: '+91-9876500008',
    email: 'contact@digitalinfra.org',
    location: 'Hyderabad',
    state: 'Telangana',
    registrationNumber: 'NGO/TS/2021/44556',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo9',
    name: 'Swachh Bharat Volunteers',
    description: 'Mobilizing communities for cleanliness drives, waste segregation, and promoting sustainable waste management practices.',
    category: 'Sanitation & Environment',
    contact: '+91-9876500009',
    email: 'info@swachhvolunteers.org',
    location: 'Ahmedabad',
    state: 'Gujarat',
    registrationNumber: 'NGO/GJ/2017/66778',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo10',
    name: 'Public Transport Advocacy Group',
    description: 'Advocating for better public transportation systems, safer bus stops, and improved commuter facilities across cities.',
    category: 'Transport & Mobility',
    contact: '+91-9876500010',
    email: 'contact@ptag.org',
    location: 'Lucknow',
    state: 'Uttar Pradesh',
    registrationNumber: 'NGO/UP/2018/88990',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo11',
    name: 'Power to People Initiative',
    description: 'Working to ensure uninterrupted electricity supply in rural and semi-urban areas through renewable energy solutions.',
    category: 'Energy & Power',
    contact: '+91-9876500011',
    email: 'hello@powertopeople.org',
    location: 'Bhopal',
    state: 'Madhya Pradesh',
    registrationNumber: 'NGO/MP/2020/11223',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo12',
    name: 'Drainage & Flood Relief Trust',
    description: 'Preventing urban flooding through drainage system maintenance, monsoon preparedness, and community awareness.',
    category: 'Disaster Management & Infrastructure',
    contact: '+91-9876500012',
    email: 'support@drainagerelief.org',
    location: 'Patna',
    state: 'Bihar',
    registrationNumber: 'NGO/BR/2019/33445',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo13',
    name: 'Smart City Citizens Forum',
    description: 'Engaging citizens in smart city development projects, promoting tech-enabled civic services and urban planning.',
    category: 'Urban Development & Technology',
    contact: '+91-9876500013',
    email: 'info@smartcityforum.org',
    location: 'Indore',
    state: 'Madhya Pradesh',
    registrationNumber: 'NGO/MP/2021/55667',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo14',
    name: 'Pavement Safety Coalition',
    description: 'Ensuring pedestrian safety through proper footpath maintenance, accessible walkways, and barrier-free infrastructure.',
    category: 'Infrastructure & Accessibility',
    contact: '+91-9876500014',
    email: 'contact@pavementsafety.org',
    location: 'Chandigarh',
    state: 'Chandigarh',
    registrationNumber: 'NGO/CH/2017/77889',
    totalDonations: 0,
    donorCount: 0,
  },
  {
    id: 'ngo15',
    name: 'Rural Electrification Mission',
    description: 'Bringing electricity to remote villages through solar power installations and grid connectivity projects.',
    category: 'Energy & Rural Development',
    contact: '+91-9876500015',
    email: 'support@ruralelectrification.org',
    location: 'Ranchi',
    state: 'Jharkhand',
    registrationNumber: 'NGO/JH/2018/99001',
    totalDonations: 0,
    donorCount: 0,
  },
];

export const mockContractors: Contractor[] = [
  { id: 'c1', name: 'ABC Construction Ltd', department: 'Public Works Department', phone: '+91-9876543210', rating: 4.5, company: 'ABC Construction Ltd', completedProjects: 156 },
  { id: 'c2', name: 'QuickFix Services', department: 'Water Supply Department', phone: '+91-9876543211', rating: 4.2, company: 'QuickFix Services Pvt Ltd', completedProjects: 89 },
  { id: 'c3', name: 'PowerLine Maintenance', department: 'Electricity Board', phone: '+91-9876543212', rating: 4.7, company: 'PowerLine Maintenance Corp', completedProjects: 234 },
  { id: 'c4', name: 'Clean City Corp', department: 'Sanitation Department', phone: '+91-9876543213', rating: 4.3, company: 'Clean City Corporation', completedProjects: 98 },
  { id: 'c5', name: 'MuniBright Solutions', department: 'Municipal Services', phone: '+91-9876543214', rating: 4.6, company: 'MuniBright Solutions Ltd', completedProjects: 167 },
  { id: 'c6', name: 'BuildPro Solutions', department: 'Public Works Department', phone: '+91-9876543215', rating: 4.7, company: 'BuildPro Solutions Pvt Ltd', completedProjects: 127 },
  { id: 'c7', name: 'RoadMaster India', department: 'Public Works Department', phone: '+91-9876543216', rating: 4.4, company: 'RoadMaster India Ltd', completedProjects: 143 },
  { id: 'c8', name: 'SwiftRepairs Co', department: 'Municipal Services', phone: '+91-9876543217', rating: 4.1, company: 'SwiftRepairs Company', completedProjects: 72 },
  { id: 'c9', name: 'GreenTech Solutions', department: 'Sanitation Department', phone: '+91-9876543218', rating: 4.8, company: 'GreenTech Solutions Pvt Ltd', completedProjects: 189 },
  { id: 'c10', name: 'UrbanFix Contractors', department: 'Public Works Department', phone: '+91-9876543219', rating: 4.3, company: 'UrbanFix Contractors Ltd', completedProjects: 104 },
];

export const mockUsers: User[] = [
  { id: 'user1', name: 'Rakesh', email: 'rakesh@example.com', role: 'citizen', trustScore: 85, reportsSubmitted: 12 },
  { id: 'user2', name: 'Priya Sharma', email: 'priya@example.com', role: 'citizen', trustScore: 92, reportsSubmitted: 8 },
  { id: 'user3', name: 'Amit Patel', email: 'amit@example.com', role: 'citizen', trustScore: 78, reportsSubmitted: 15 },
  { id: 'auth1', name: 'Municipal Officer', email: 'officer@janmarg.gov', role: 'authority', trustScore: 100 },
];

const locations = [
  { lat: 28.6139, lng: 77.2090, address: 'Connaught Place, New Delhi', city: 'New Delhi', state: 'Delhi' as const, pincode: '110001' },
  { lat: 28.5355, lng: 77.3910, address: 'Noida Sector 18', city: 'Noida', state: 'Uttar Pradesh' as const, pincode: '201301' },
  { lat: 28.7041, lng: 77.1025, address: 'Rohini Sector 7', city: 'Delhi', state: 'Delhi' as const, pincode: '110085' },
  { lat: 30.7333, lng: 76.7794, address: 'Sector 17, Chandigarh', city: 'Chandigarh', state: 'Chandigarh' as const, pincode: '160017' },
  { lat: 28.6692, lng: 77.4538, address: 'Kaushambi, Ghaziabad', city: 'Ghaziabad', state: 'Uttar Pradesh' as const, pincode: '201010' },
  { lat: 19.0760, lng: 72.8777, address: 'Andheri, Mumbai', city: 'Mumbai', state: 'Maharashtra' as const, pincode: '400053' },
  { lat: 12.9716, lng: 77.5946, address: 'MG Road, Bangalore', city: 'Bangalore', state: 'Karnataka' as const, pincode: '560001' },
  { lat: 26.9124, lng: 75.7873, address: 'Jaipur City Center', city: 'Jaipur', state: 'Rajasthan' as const, pincode: '302001' },
  { lat: 23.0225, lng: 72.5714, address: 'Ahmedabad Central', city: 'Ahmedabad', state: 'Gujarat' as const, pincode: '380001' },
  { lat: 13.0827, lng: 80.2707, address: 'T Nagar, Chennai', city: 'Chennai', state: 'Tamil Nadu' as const, pincode: '600017' },
  { lat: 22.5726, lng: 88.3639, address: 'Park Street, Kolkata', city: 'Kolkata', state: 'West Bengal' as const, pincode: '700016' },
  { lat: 30.3165, lng: 78.0322, address: 'Rajpur Road, Dehradun', city: 'Dehradun', state: 'Uttarakhand' as const, pincode: '248001' },
  { lat: 31.1048, lng: 77.1734, address: 'Mall Road, Shimla', city: 'Shimla', state: 'Himachal Pradesh' as const, pincode: '171001' },
  { lat: 30.9010, lng: 75.8573, address: 'Model Town, Ludhiana', city: 'Ludhiana', state: 'Punjab' as const, pincode: '141002' },
  { lat: 28.4595, lng: 77.0266, address: 'Cyber City, Gurgaon', city: 'Gurgaon', state: 'Haryana' as const, pincode: '122002' },
];

export const generateMockIssues = (): Issue[] => {
  const baseIssues: Omit<Issue, 'aiInsights'>[] = [
    {
      id: '1',
      title: 'Large Pothole on Main Road',
      description: 'There is a dangerous pothole approximately 2 feet wide and 6 inches deep on the main road near the market. It has caused multiple vehicle accidents and poses a serious safety hazard during monsoon.',
      category: 'roads',
      location: locations[0],
      status: 'bidding',
      imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80', // Indian road pothole
      userId: 'user1',
      userName: 'Rakesh',
      isAnonymous: false,
      upvotes: 45,
      downvotes: 2,
      votedBy: ['user2', 'user3'],
      comments: [
        { id: 'c1', issueId: '1', userId: 'user2', userName: 'Priya Sharma', text: 'This has been a problem for months! Thank you for reporting.', timestamp: Date.now() - 86400000 },
        { id: 'c2', issueId: '1', userId: 'auth1', userName: 'Municipal Officer', text: 'Reviewing contractor bids for this project.', timestamp: Date.now() - 43200000, isOfficial: true, userRole: 'authority' },
      ],
      timeline: [
        { id: 't1', issueId: '1', type: 'created', description: 'Issue reported by Rakesh', timestamp: Date.now() - 172800000, userId: 'user1', userName: 'Rakesh' },
        { id: 't2', issueId: '1', type: 'status_change', description: 'Status changed to Bidding', timestamp: Date.now() - 86400000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      createdAt: Date.now() - 172800000,
      updatedAt: Date.now() - 43200000,
      department: 'Public Works Department',
      bids: [
        {
          id: 'bid-1',
          issueId: '1',
          collaboratorId: 'collab1',
          collaboratorName: 'BuildPro Solutions',
          company: 'BuildPro Solutions Pvt Ltd',
          amount: 42000,
          duration: 5,
          proposal: 'We have specialized equipment and 10+ years experience in road repair. Our team can complete this work efficiently with minimal traffic disruption. We use high-quality materials that last 5+ years.',
          timestamp: Date.now() - 21600000,
          status: 'pending',
          rating: 4.7,
          completedProjects: 127,
        },
        {
          id: 'bid-2',
          issueId: '1',
          collaboratorId: 'collab2',
          collaboratorName: 'RoadFix India',
          company: 'RoadFix India Limited',
          amount: 45000,
          duration: 4,
          proposal: 'We can start immediately and complete within 4 days. ISO certified and government approved contractor with proven track record.',
          timestamp: Date.now() - 18000000,
          status: 'pending',
          rating: 4.5,
          completedProjects: 98,
        },
        {
          id: 'bid-3',
          issueId: '1',
          collaboratorId: 'collab3',
          collaboratorName: 'QuickRepair Co',
          company: 'QuickRepair Company',
          amount: 38000,
          duration: 7,
          proposal: 'Budget-friendly solution with quality materials. We have done similar work in nearby areas.',
          timestamp: Date.now() - 14400000,
          status: 'pending',
          rating: 4.2,
          completedProjects: 56,
        },
      ],
    },
    {
      id: '2',
      title: 'Water Pipe Leakage',
      description: 'Continuous water leakage from the main supply line for the past 3 days. Water is being wasted and the road has become slippery and hazardous.',
      category: 'water',
      location: locations[1],
      status: 'in-progress',
      imageUrl: 'https://images.unsplash.com/photo-1584555684040-bad07f2bc6ce?w=800&q=80', // Water pipe leakage India
      userId: 'user2',
      userName: 'Priya Sharma',
      isAnonymous: false,
      upvotes: 32,
      downvotes: 0,
      votedBy: ['user1'],
      comments: [
        { id: 'c3', issueId: '2', userId: 'user3', userName: 'Amit Patel', text: 'Same issue in my street! Hope this gets fixed soon.', timestamp: Date.now() - 7200000 },
        { id: 'c3b', issueId: '2', userId: 'auth1', userName: 'Municipal Officer', text: 'Repair work in progress. Expected completion in 2 days.', timestamp: Date.now() - 86400000, isOfficial: true },
      ],
      timeline: [
        { id: 't4', issueId: '2', type: 'created', description: 'Issue reported by Priya Sharma', timestamp: Date.now() - 259200000, userId: 'user2', userName: 'Priya Sharma' },
        { id: 't5', issueId: '2', type: 'assigned', description: 'Assigned to QuickFix Services', timestamp: Date.now() - 172800000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't5b', issueId: '2', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 86400000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[1],
      createdAt: Date.now() - 259200000,
      updatedAt: Date.now() - 86400000,
      department: 'Water Supply Department',
    },
    {
      id: '3',
      title: 'Street Light Not Working',
      description: 'The street light near the park entrance has not been working for over a week. This creates safety concerns during evening hours.',
      category: 'street-lights',
      location: locations[2],
      status: 'resolved',
      imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80', // Indian street light
      resolutionImageUrl: 'https://images.unsplash.com/photo-1612709940821-088f5509b7c4?w=800&q=80', // Street light repaired
      resolutionImageUploadedBy: 'auth1',
      resolutionImageUploadedAt: Date.now() - 345600000,
      userId: 'user3',
      userName: 'Amit Patel',
      isAnonymous: false,
      upvotes: 18,
      downvotes: 1,
      votedBy: [],
      comments: [],
      timeline: [
        { id: 't6', issueId: '3', type: 'created', description: 'Issue reported by Amit Patel', timestamp: Date.now() - 604800000, userId: 'user3', userName: 'Amit Patel' },
        { id: 't7', issueId: '3', type: 'assigned', description: 'Assigned to MuniBright Solutions', timestamp: Date.now() - 518400000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't8', issueId: '3', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 432000000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't9', issueId: '3', type: 'closed', description: 'Issue marked as resolved', timestamp: Date.now() - 345600000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[4],
      createdAt: Date.now() - 604800000,
      updatedAt: Date.now() - 345600000,
      department: 'Municipal Services',
    },
    {
      id: '4',
      title: 'Garbage Overflow at Collection Point',
      description: 'The garbage collection point is overflowing and has not been cleared for several days. This is causing foul smell and attracting stray animals.',
      category: 'sanitation',
      location: locations[3],
      status: 'bidding',
      imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800',
      userId: 'anon1',
      userName: 'Anonymous',
      isAnonymous: true,
      upvotes: 67,
      downvotes: 3,
      votedBy: ['user1', 'user2', 'user3'],
      comments: [
        { id: 'c4', issueId: '4', userId: 'user1', userName: 'Rakesh', text: 'This is a serious health hazard. Needs immediate attention!', timestamp: Date.now() - 21600000 },
        { id: 'c5', issueId: '4', userId: 'user2', userName: 'Priya Sharma', text: 'Reported the same issue last month. Still no action taken.', timestamp: Date.now() - 14400000 },
      ],
      timeline: [
        { id: 't10', issueId: '4', type: 'created', description: 'Issue reported anonymously', timestamp: Date.now() - 86400000, userId: 'anon1', userName: 'Anonymous' },
        { id: 't10b', issueId: '4', type: 'bidding_opened', description: 'Bidding opened for contractors', timestamp: Date.now() - 43200000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      bids: [
        { id: 'bid1', issueId: '4', collaboratorId: 'c4', collaboratorName: 'Clean City Corp', company: 'Clean City Corporation', amount: 12000, duration: 2, proposal: 'We specialize in waste management with modern equipment. We can clean and sanitize the area within 2 days.', timestamp: Date.now() - 28800000, status: 'pending', rating: 4.3, completedProjects: 98 },
        { id: 'bid2', issueId: '4', collaboratorId: 'c5', collaboratorName: 'MuniBright Solutions', company: 'MuniBright Solutions Ltd', amount: 10500, duration: 3, proposal: 'Comprehensive cleanup with eco-friendly methods and preventive measures to avoid future overflow.', timestamp: Date.now() - 21600000, status: 'pending', rating: 4.6, completedProjects: 167 },
      ],
      createdAt: Date.now() - 86400000,
      updatedAt: Date.now() - 21600000,
      department: 'Sanitation Department',
    },
    {
      id: '5',
      title: 'Power Outage - Transformer Issue',
      description: 'Frequent power cuts in the area due to faulty transformer. Outages last 4-6 hours daily affecting residential and commercial establishments.',
      category: 'electricity',
      location: locations[4],
      status: 'in-progress',
      imageUrl: 'https://images.unsplash.com/photo-1694325319663-768912f32bab?w=800&q=80', // Indian electrical transformer
      userId: 'user1',
      userName: 'Rakesh',
      isAnonymous: false,
      upvotes: 89,
      downvotes: 1,
      votedBy: ['user2', 'user3'],
      comments: [
        { id: 'c6', issueId: '5', userId: 'auth1', userName: 'Municipal Officer', text: 'Electricity Board has been notified. Transformer replacement scheduled for tomorrow.', timestamp: Date.now() - 28800000, isOfficial: true },
      ],
      timeline: [
        { id: 't11', issueId: '5', type: 'created', description: 'Issue reported by Rakesh', timestamp: Date.now() - 172800000, userId: 'user1', userName: 'Rakesh' },
        { id: 't12', issueId: '5', type: 'assigned', description: 'Assigned to PowerLine Maintenance', timestamp: Date.now() - 86400000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't13', issueId: '5', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 43200000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[2],
      createdAt: Date.now() - 172800000,
      updatedAt: Date.now() - 43200000,
      department: 'Electricity Board',
    },
    {
      id: '6',
      title: 'Blocked Drainage Causing Flooding',
      description: 'The drainage system is completely blocked, causing waterlogging during rains. Water enters nearby homes and shops.',
      category: 'drainage',
      location: locations[5],
      status: 'bidding',
      imageUrl: 'https://images.unsplash.com/photo-1665905276136-4d9ddb24fc92?w=800&q=80', // Drainage flooding India
      userId: 'user2',
      userName: 'Priya Sharma',
      isAnonymous: false,
      upvotes: 54,
      downvotes: 0,
      votedBy: ['user1', 'user3'],
      comments: [],
      timeline: [
        { id: 't14', issueId: '6', type: 'created', description: 'Issue reported by Priya Sharma', timestamp: Date.now() - 43200000, userId: 'user2', userName: 'Priya Sharma' },
        { id: 't14b', issueId: '6', type: 'bidding_opened', description: 'Bidding opened for contractors', timestamp: Date.now() - 21600000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      bids: [
        { id: 'bid3', issueId: '6', collaboratorId: 'c1', collaboratorName: 'ABC Construction Ltd', company: 'ABC Construction Ltd', amount: 38000, duration: 7, proposal: 'Complete drainage system clearance and repair with warranty. Experienced team with latest equipment.', timestamp: Date.now() - 14400000, status: 'pending', rating: 4.5, completedProjects: 156 },
      ],
      createdAt: Date.now() - 43200000,
      updatedAt: Date.now() - 14400000,
      department: 'Drainage Department',
    },
    {
      id: '7',
      title: 'Bus Stop Shelter Damaged',
      description: 'The bus stop shelter roof is damaged and provides no protection from rain or sun. Needs urgent repair.',
      category: 'public-transport',
      location: locations[6],
      status: 'in-progress',
      imageUrl: 'https://images.unsplash.com/photo-1715883532478-bf53eb65b05a?w=800&q=80', // Damaged bus stop shelter
      userId: 'user3',
      userName: 'Amit Patel',
      isAnonymous: false,
      upvotes: 23,
      downvotes: 2,
      votedBy: [],
      comments: [
        { id: 'c7b', issueId: '7', userId: 'auth1', userName: 'Municipal Officer', text: 'Repair work has begun. New shelter being installed.', timestamp: Date.now() - 172800000, isOfficial: true },
      ],
      timeline: [
        { id: 't15', issueId: '7', type: 'created', description: 'Issue reported by Amit Patel', timestamp: Date.now() - 432000000, userId: 'user3', userName: 'Amit Patel' },
        { id: 't16', issueId: '7', type: 'assigned', description: 'Assigned to ABC Construction Ltd', timestamp: Date.now() - 259200000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't16b', issueId: '7', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 172800000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[0],
      createdAt: Date.now() - 432000000,
      updatedAt: Date.now() - 172800000,
      department: 'Transport Authority',
    },
    {
      id: '8',
      title: 'Broken Pavement Causing Accidents',
      description: 'Pavement is broken and uneven, causing people to trip and fall. Several minor injuries reported.',
      category: 'roads',
      location: locations[7],
      status: 'submitted',
      imageUrl: 'https://images.unsplash.com/photo-1724497397783-81102d4dfa5d?w=800&q=80', // Broken pavement India
      userId: 'anon2',
      userName: 'Anonymous',
      isAnonymous: true,
      upvotes: 41,
      downvotes: 0,
      votedBy: ['user1', 'user2'],
      comments: [
        { id: 'c7', issueId: '8', userId: 'user3', userName: 'Amit Patel', text: 'My elderly neighbor fell here last week. This needs immediate attention.', timestamp: Date.now() - 10800000 },
      ],
      timeline: [
        { id: 't17', issueId: '8', type: 'created', description: 'Issue reported anonymously', timestamp: Date.now() - 21600000, userId: 'anon2', userName: 'Anonymous' },
      ],
      createdAt: Date.now() - 21600000,
      updatedAt: Date.now() - 21600000,
      department: 'Public Works Department',
    },
    {
      id: '9',
      title: 'Cracked Road Surface',
      description: 'Major cracks on highway causing vehicle damage. Multiple complaints received from commuters.',
      category: 'roads',
      location: locations[8],
      status: 'resolved',
      imageUrl: 'https://images.unsplash.com/photo-1753127096071-55bebb47d9f2?w=800&q=80', // Road cracks India
      resolutionImageUrl: 'https://images.unsplash.com/photo-1663001822575-a2b7f831491e?w=800&q=80', // Road repaired
      resolutionImageUploadedBy: 'c6',
      resolutionImageUploadedAt: Date.now() - 518400000,
      userId: 'user1',
      userName: 'Rakesh',
      isAnonymous: false,
      upvotes: 72,
      downvotes: 3,
      votedBy: ['user2', 'user3'],
      comments: [
        { id: 'c8', issueId: '9', userId: 'auth1', userName: 'Municipal Officer', text: 'Road resurfacing completed successfully.', timestamp: Date.now() - 518400000, isOfficial: true },
      ],
      timeline: [
        { id: 't18', issueId: '9', type: 'created', description: 'Issue reported by Rakesh', timestamp: Date.now() - 1209600000, userId: 'user1', userName: 'Rakesh' },
        { id: 't19', issueId: '9', type: 'assigned', description: 'Assigned to BuildPro Solutions', timestamp: Date.now() - 864000000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't20', issueId: '9', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 691200000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't21', issueId: '9', type: 'closed', description: 'Issue resolved and verified', timestamp: Date.now() - 518400000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[5],
      createdAt: Date.now() - 1209600000,
      updatedAt: Date.now() - 518400000,
      department: 'Public Works Department',
    },
    {
      id: '10',
      title: 'Public Toilet Unhygienic',
      description: 'Public toilet facility in market area is in terrible condition, needs cleaning and maintenance.',
      category: 'sanitation',
      location: locations[9],
      status: 'resolved',
      imageUrl: 'https://images.unsplash.com/photo-1679841667395-99befa73d130?w=800&q=80', // Public toilet India
      resolutionImageUrl: 'https://images.unsplash.com/photo-1561891615-a79506c75afe?w=800&q=80', // Cleaned area
      resolutionImageUploadedBy: 'c4',
      resolutionImageUploadedAt: Date.now() - 691200000,
      userId: 'user2',
      userName: 'Priya Sharma',
      isAnonymous: false,
      upvotes: 56,
      downvotes: 2,
      votedBy: ['user1', 'user3'],
      comments: [],
      timeline: [
        { id: 't22', issueId: '10', type: 'created', description: 'Issue reported by Priya Sharma', timestamp: Date.now() - 1382400000, userId: 'user2', userName: 'Priya Sharma' },
        { id: 't23', issueId: '10', type: 'assigned', description: 'Assigned to Clean City Corp', timestamp: Date.now() - 1036800000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't24', issueId: '10', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 864000000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't25', issueId: '10', type: 'closed', description: 'Facility cleaned and sanitized', timestamp: Date.now() - 691200000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[3],
      createdAt: Date.now() - 1382400000,
      updatedAt: Date.now() - 691200000,
      department: 'Sanitation Department',
    },
    {
      id: '11',
      title: 'Water Supply Interruption',
      description: 'No water supply in the locality for 48 hours. Residents facing severe hardship.',
      category: 'water',
      location: locations[10],
      status: 'resolved',
      imageUrl: 'https://images.unsplash.com/photo-1680008702835-d79e376a5f79?w=800&q=80', // Water shortage India
      resolutionImageUrl: 'https://images.unsplash.com/photo-1702658508397-4f0cf73aa23e?w=800&q=80', // Water restored
      resolutionImageUploadedBy: 'c2',
      resolutionImageUploadedAt: Date.now() - 432000000,
      userId: 'user3',
      userName: 'Amit Patel',
      isAnonymous: false,
      upvotes: 94,
      downvotes: 0,
      votedBy: ['user1', 'user2'],
      comments: [
        { id: 'c9', issueId: '11', userId: 'auth1', userName: 'Municipal Officer', text: 'Water supply restored. Pump has been repaired.', timestamp: Date.now() - 432000000, isOfficial: true },
      ],
      timeline: [
        { id: 't26', issueId: '11', type: 'created', description: 'Issue reported by Amit Patel', timestamp: Date.now() - 777600000, userId: 'user3', userName: 'Amit Patel' },
        { id: 't27', issueId: '11', type: 'assigned', description: 'Assigned to QuickFix Services', timestamp: Date.now() - 604800000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't28', issueId: '11', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 518400000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't29', issueId: '11', type: 'closed', description: 'Water supply fully restored', timestamp: Date.now() - 432000000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[1],
      createdAt: Date.now() - 777600000,
      updatedAt: Date.now() - 432000000,
      department: 'Water Supply Department',
    },
    {
      id: '12',
      title: 'Park Waste Accumulation',
      description: 'Children park has accumulated waste and garbage. Needs immediate cleanup for children safety.',
      category: 'parks',
      location: locations[11],
      status: 'resolved',
      imageUrl: 'https://images.unsplash.com/photo-1704980524963-18071a25cb42?w=800&q=80', // Park garbage India
      resolutionImageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&q=80', // Park cleaned
      resolutionImageUploadedBy: 'c9',
      resolutionImageUploadedAt: Date.now() - 259200000,
      userId: 'anon3',
      userName: 'Anonymous',
      isAnonymous: true,
      upvotes: 38,
      downvotes: 1,
      votedBy: ['user2'],
      comments: [],
      timeline: [
        { id: 't30', issueId: '12', type: 'created', description: 'Issue reported anonymously', timestamp: Date.now() - 518400000, userId: 'anon3', userName: 'Anonymous' },
        { id: 't31', issueId: '12', type: 'assigned', description: 'Assigned to GreenTech Solutions', timestamp: Date.now() - 432000000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't32', issueId: '12', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 345600000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't33', issueId: '12', type: 'closed', description: 'Park cleaned and sanitized', timestamp: Date.now() - 259200000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[8],
      createdAt: Date.now() - 518400000,
      updatedAt: Date.now() - 259200000,
      department: 'Parks & Recreation',
    },
    {
      id: '13',
      title: 'Dangerous Hanging Electricity Cables',
      description: 'Low-hanging electricity cables pose serious safety risk. Could electrocute pedestrians during rain.',
      category: 'electricity',
      location: locations[12],
      status: 'in-progress',
      imageUrl: 'https://images.unsplash.com/photo-1512759925926-28b2607d28fe?w=800&q=80', // Hanging cables India
      userId: 'user1',
      userName: 'Rakesh',
      isAnonymous: false,
      upvotes: 103,
      downvotes: 1,
      votedBy: ['user2', 'user3'],
      comments: [
        { id: 'c10', issueId: '13', userId: 'user2', userName: 'Priya Sharma', text: 'This is extremely dangerous! Please fix immediately.', timestamp: Date.now() - 43200000 },
        { id: 'c11', issueId: '13', userId: 'auth1', userName: 'Municipal Officer', text: 'Electricity Board team on site. Cables being reorganized.', timestamp: Date.now() - 21600000, isOfficial: true },
      ],
      timeline: [
        { id: 't34', issueId: '13', type: 'created', description: 'Issue reported by Rakesh', timestamp: Date.now() - 345600000, userId: 'user1', userName: 'Rakesh' },
        { id: 't35', issueId: '13', type: 'assigned', description: 'Assigned to PowerLine Maintenance', timestamp: Date.now() - 172800000, userId: 'auth1', userName: 'Municipal Officer' },
        { id: 't36', issueId: '13', type: 'status_change', description: 'Status changed to In Progress', timestamp: Date.now() - 86400000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[2],
      createdAt: Date.now() - 345600000,
      updatedAt: Date.now() - 21600000,
      department: 'Electricity Board',
    },
    {
      id: '14',
      title: 'Water Tank Leakage in Residential Area',
      description: 'Overhead water tank has major leakage. Water wastage and structural damage risk.',
      category: 'water',
      location: locations[13],
      status: 'submitted',
      imageUrl: 'https://images.unsplash.com/photo-1709637236431-efb65a55b415?w=800&q=80', // Water tank leakage India
      userId: 'user2',
      userName: 'Priya Sharma',
      isAnonymous: false,
      upvotes: 28,
      downvotes: 1,
      votedBy: ['user1'],
      comments: [],
      timeline: [
        { id: 't37', issueId: '14', type: 'created', description: 'Issue reported by Priya Sharma', timestamp: Date.now() - 129600000, userId: 'user2', userName: 'Priya Sharma' },
      ],
      createdAt: Date.now() - 129600000,
      updatedAt: Date.now() - 129600000,
      department: 'Water Supply Department',
    },
    {
      id: '15',
      title: 'Traffic Signal Malfunction',
      description: 'Traffic lights not functioning properly at major intersection. Causing traffic chaos and accidents.',
      category: 'other',
      location: locations[14],
      status: 'submitted',
      imageUrl: 'https://images.unsplash.com/photo-1579332310389-87bce06ae797?w=800&q=80', // Traffic signal India
      userId: 'user3',
      userName: 'Amit Patel',
      isAnonymous: false,
      upvotes: 78,
      downvotes: 2,
      votedBy: ['user1', 'user2'],
      comments: [
        { id: 'c12', issueId: '15', userId: 'user1', userName: 'Rakesh', text: 'Witnessed a near-miss accident here yesterday. Very dangerous!', timestamp: Date.now() - 7200000 },
      ],
      timeline: [
        { id: 't38', issueId: '15', type: 'created', description: 'Issue reported by Amit Patel', timestamp: Date.now() - 86400000, userId: 'user3', userName: 'Amit Patel' },
      ],
      createdAt: Date.now() - 86400000,
      updatedAt: Date.now() - 86400000,
      department: 'Traffic Police',
    },
    {
      id: '16',
      title: 'Broken Street Light - Multiple Poles',
      description: 'Entire street section has non-functional lights. Safety concern for evening commuters and residents.',
      category: 'street-lights',
      location: locations[0],
      status: 'assigned',
      imageUrl: 'https://images.unsplash.com/photo-1642388533218-2aa1e969df6c?w=800&q=80', // Street light pole India
      userId: 'user1',
      userName: 'Rakesh',
      isAnonymous: false,
      upvotes: 52,
      downvotes: 0,
      votedBy: ['user2', 'user3'],
      comments: [],
      timeline: [
        { id: 't39', issueId: '16', type: 'created', description: 'Issue reported by Rakesh', timestamp: Date.now() - 302400000, userId: 'user1', userName: 'Rakesh' },
        { id: 't40', issueId: '16', type: 'assigned', description: 'Assigned to MuniBright Solutions', timestamp: Date.now() - 172800000, userId: 'auth1', userName: 'Municipal Officer' },
      ],
      assignedContractor: mockContractors[4],
      createdAt: Date.now() - 302400000,
      updatedAt: Date.now() - 172800000,
      department: 'Municipal Services',
    },
    {
      id: '17',
      title: 'Sewage Overflow on Main Street',
      description: 'Sewage water overflowing from manhole cover. Unbearable stench and health hazard.',
      category: 'sanitation',
      location: locations[1],
      status: 'submitted',
      imageUrl: 'https://images.unsplash.com/photo-1561891615-a79506c75afe?w=800&q=80', // Sewage overflow India
      userId: 'anon4',
      userName: 'Anonymous',
      isAnonymous: true,
      upvotes: 112,
      downvotes: 4,
      votedBy: ['user1', 'user2', 'user3'],
      comments: [
        { id: 'c13', issueId: '17', userId: 'user2', userName: 'Priya Sharma', text: 'Disgusting! My children cannot even play outside because of this.', timestamp: Date.now() - 14400000 },
        { id: 'c14', issueId: '17', userId: 'user3', userName: 'Amit Patel', text: 'This has been ongoing for a week. Where is the municipality?', timestamp: Date.now() - 10800000 },
      ],
      timeline: [
        { id: 't41', issueId: '17', type: 'created', description: 'Issue reported anonymously', timestamp: Date.now() - 172800000, userId: 'anon4', userName: 'Anonymous' },
      ],
      createdAt: Date.now() - 172800000,
      updatedAt: Date.now() - 172800000,
      department: 'Sanitation Department',
    },
  ];

  // Generate AI insights for each issue
  const issues: Issue[] = baseIssues.map(issue => {
    const baseAI = generateAIInsights(issue as Issue, baseIssues as Issue[]);
    return {
      ...issue,
      aiInsights: generateEnhancedAIInsights(issue as Issue, baseIssues as Issue[], baseAI),
    };
  });

  return issues;
};